replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-1.amazonaws.com/payment-service 
  pullPolicy: Always
  tag: "dev"

fullnameOverride: "payment-service-dev"

containerPort: 3000

service:
  type: NodePort
  port: 80
  protocol: TCP
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/success-codes: '404'
    alb.ingress.kubernetes.io/group.name: main
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:667950714614:certificate/aa68bfac-fe5d-4b63-972e-91aa3e12a669
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: test-dev-payment-service.totem-explorer.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: payment-service-dev
            servicePort: 80
  tls: []

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownSeconds: 3

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

env:
      PORT: ""
      REDIS_STORAGE_URI: ""
      MONGODB_DATABASE: ""
      PROVIDER_RPC: ""
      PROVIDER_ABI_FILEPATH: ""
      PROVIDER_TOKEN_ADDRESS: ""
      ASSETS: ""
      MONGODB_URI: ""
      PROVIDER_PRIVATE_KEY: ""