# Default values for kor-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-1.amazonaws.com/totem-payment-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "prod"

fullnameOverride: "totem-payment-service"

containerPort: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:667950714614:certificate/aa68bfac-fe5d-4b63-972e-91aa3e12a669
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: test-totem-payment-service.totem-explorer.com
      paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: totem-payment-service
            servicePort: 80
  tls: []

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

envFrom:
    - secretRef:
        name: token-faucet
env:
      PORT:
      MATIC_AMOUNT:
      USDC_AMOUNT:
