apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: minter-assets
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
            - name: REDIS_STORAGE_URI
              value: redis://redis:6379/0
            - name: MONGODB_DATABASE
              value: assets
            - name: PROVIDER_RPC
              value: https://matic-mumbai.chainstacklabs.com
            - name: PROVIDER_ABI_FILEPATH
              value: contract/erc20.abi.json
            - name: PROVIDER_TOKEN_ADDRESS
              value: 0xB408CC68A12d7d379434E794880403393B64E44b
          envFrom:
            - secretRef:
                name: payment
          image: 667950714614.dkr.ecr.us-east-2.amazonaws.com/payment-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
