apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: PORT
              value:
            - name: REDIS_STORAGE_URI
              value:
            - name: PROVIDER_PRIVATE_KEY
              value:
            - name: PROVIDER_RPC
              value:
            - name: PROVIDER_ABI_FILEPATH
              value:
            - name: PROVIDER_TOKEN_ADDRESS
              value:
          image: 667950714614.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
